# Danube Broker Configuration for Docker Compose with MinIO S3 Storage
# Optimized for cloud-ready deployment with AWS S3 compatibility

# Danube cluster name
cluster_name: "DANUBE_DOCKER_CLUSTER"

# Danube Broker hostname
# Using 0.0.0.0 to bind to all interfaces within container
broker_host: "0.0.0.0"

# Ports for the Danube broker services
# Port for gRPC communication with the broker
broker_port: 6650
# Port for the Admin API
admin_port: 50051
# Port for Prometheus exporter
prom_port: 9040

# Metadata Persistent Store address (ETCD)
# Using container hostname for service discovery
meta_store_host: "etcd"
# Port for etcd
meta_store_port: 2379

# Namespaces to be created on boot
bootstrap_namespaces:
  - "default"
  - "examples"
  - "testing"

# Allow producers to auto-create topics when missing
auto_create_topics: true

# Security Configuration - Disabled for development
auth:
  mode: none # Options: none, tls, tlswithjwt

# WAL and Cloud Storage Configuration
# Configured for MinIO S3-compatible storage
wal_cloud:
  wal:
    dir: "./danube-data/wal"
    file_name: "wal.log"
    cache_capacity: 1024
    # WAL file sync configuration, drive flush cadence and checkpoint frequency
    file_sync:
      interval_ms: 5000         # Default:Flush every 5s to reduce fsync pressure while keeping WAL checkpoints reasonably fresh
      max_batch_bytes: 10485760 # Default: 10 MiB writer batch
    # WAL file rotation configuration, balances file size and directory churn
    rotation:
      max_bytes: 536870912      # Default: 512 MiB WAL file size
      # max_hours: 24           # Optional time-based rotation (in hours)
    retention:
      time_minutes: 2880            # 48 hours (conservative production default)
      size_mb: 20480                # 20 GiB per topic
      check_interval_minutes: 5     # run every 5 minutes

  # Uploader configuration for background S3 uploads
  uploader:
    enabled: true
    interval_seconds: 10       # Default: Upload every 10 seconds for testing, Default is every 5 minutes
    root_prefix: "/danube-data"

  # Cloud storage backend - MinIO S3 configuration
  cloud:
    backend: "s3"
    root: "s3://danube-messages/cluster-data"  # S3 bucket and prefix
    region: "us-east-1"
    endpoint: "http://minio:9000"              # MinIO endpoint within Docker network
    access_key: "minioadmin"         # From environment variable
    secret_key: "minioadmin123"     # From environment variable
    anonymous: false
    virtual_host_style: false

  # Metadata configuration
  metadata:
    etcd_endpoint: "etcd:2379"
    in_memory: false

# Broker policies optimized for development and testing
policies:
  # Allow unlimited producers for testing
  max_producers_per_topic: 0

  # Allow unlimited subscriptions for testing
  max_subscriptions_per_topic: 0

  # Allow unlimited consumers for testing
  max_consumers_per_topic: 0

  # Allow unlimited consumers per subscription for testing
  max_consumers_per_subscription: 0

  # Allow high publish rate for performance testing
  max_publish_rate: 0

  # Allow high dispatch rate for performance testing
  max_dispatch_rate: 0

  # Allow high subscription dispatch rate for performance testing
  max_subscription_dispatch_rate: 0

  # Allow larger messages for testing (50 MB)
  max_message_size: 52428800
