# Danube cluster name
cluster_name: "MY_CLUSTER"

# Danube Broker hostname
# Hostname or IP address shared by Broker, Admin API, and Prometheus exporter
broker_host: "0.0.0.0"

# Ports for the Danube broker services
# Port for gRPC communication with the broker
broker_port: 6650
# Port for the Admin API
admin_port: 50051
# Port for Prometheus exporter
prom_port: 9040

# Metadata Persistent Store address (e.g., etcd)
# Hostname or IP for etcd
meta_store_host: "127.0.0.1"
# Port for etcd or metadata store
meta_store_port: 2379

# Namespaces to be created on boot
bootstrap_namespaces:
  - "default"

# Security Configuration
auth:
  mode: tls # Options: none, tls, tlswithjwt
  tls:
    cert_file: "./cert/server-cert.pem"
    key_file: "./cert/server-key.pem"
    ca_file: "./cert/ca-cert.pem"
    verify_client: false
  jwt:
    secret_key: "your-secret-key"
    issuer: "danube-auth"
    expiration_time: 3600 # in seconds

# Messsage Storage Configuration
storage:
  # Valid options: local, remote
  # the "inmemory" should be used only for local testing !
  type: "inmemory"

  # Cache configuration
  # if the segment is not found in the cache, it will be loaded from the storage
  cache:
    max_capacity: 100 # number of segment entries in the cache
    # A cached entry will be expired after the specified duration past from get or insert.
    time_to_idle: 10 # in minutes

  # Disk storage configuration
  local_config:
    path: "./your_directory"

  # Managed storage configuration, connect to external grpc storage layer
  remote_config:
    endpoint: "grpc://0.0.0.0:50060"
    use_tls: false
    ca_file: "ca-cert.pem"
    connection_timeout: 5000

# Broker policies, that can be overwritten by namespace / topic policies
policies:
  # Limits the maximum number of producers that can simultaneously publish messages to a specific topic.
  # Default is 0, unlimited.
  max_producers_per_topic: 0

  # Limits the maximum number of subscriptions that can be created on the topic.
  # Default is 0, unlimited.
  max_subscriptions_per_topic: 0

  # Limits the maximum number of consumers that can simultaneously consume messages from a specific topic.
  # Default is 0, unlimited.
  max_consumers_per_topic: 0

  # Limits the maximum number of consumers that can simultaneously use a single subscription on a topic.
  # Default is 0, unlimited.
  max_consumers_per_subscription: 0

  # Defines the Max publish rate (number of messages and/or bytes per second) for producers publishing to the topic.
  # Default is 0, unlimited.
  max_publish_rate: 0

  # Defines the Max dispatch rate (number of messages and/or bytes per second) for the topic.
  # Default is 0, unlimited.
  max_dispatch_rate: 0

  # Defines the dispatch rate for each subscription on the topic.
  # Default is 0, unlimited.
  max_subscription_dispatch_rate: 0

  # Limits the maximum size of a single message that can be published to the topic.
  # Default is 10 MB
  max_message_size: 10485760 # in bytes which means 10 MB
