// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateEdgeTopicRequest {
    /// Full topic path, e.g. "/edge1/sensor_temp"
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    /// Optional schema for the topic
    #[prost(message, optional, tag = "2")]
    pub schema: ::core::option::Option<EdgeSchemaInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EdgeSchemaInfo {
    /// Schema subject name
    #[prost(string, tag = "1")]
    pub subject: ::prost::alloc::string::String,
    /// "json_schema", "avro", "protobuf", "string", "bytes"
    #[prost(string, tag = "2")]
    pub schema_type: ::prost::alloc::string::String,
    /// Raw schema definition
    #[prost(bytes = "vec", tag = "3")]
    pub schema_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateEdgeTopicResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicateBatch {
    /// Must be a created edge topic
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<ReplicateMessage>,
    /// Highest edge WAL offset in this batch
    #[prost(uint64, tag = "3")]
    pub batch_last_offset: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicateMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(map = "string, string", tag = "2")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Original WAL offset on the edge
    #[prost(uint64, tag = "3")]
    pub edge_offset: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplicateAck {
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    /// Cluster confirms: all edge offsets ≤ this are stored
    #[prost(uint64, tag = "2")]
    pub acked_offset: u64,
}
/// Generated client implementations.
pub mod edge_replicator_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Edge → Cluster replication service.
    ///
    /// Hosted on the cluster broker's gRPC port, behind the standard auth interceptor.
    /// Edge brokers authenticate using the same mechanisms as any client:
    ///
    /// * JWT token (via `authorization` header) — scoped to the edge's namespace
    /// * mTLS + internal-broker header — for trusted infrastructure
    ///
    /// The admin pre-provisions: namespace, JWT token, RBAC binding with Replicate permission.
    #[derive(Debug, Clone)]
    pub struct EdgeReplicatorServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EdgeReplicatorServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EdgeReplicatorServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EdgeReplicatorServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EdgeReplicatorServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Create a topic on the cluster for edge replication.
        ///
        /// * Validates that the topic belongs to a namespace the caller has access to
        /// * Creates topic metadata (always Reliable dispatch strategy)
        /// * Creates WAL via StorageFactory
        ///  Auth: requires ManageTopic permission on the topic's namespace.
        pub async fn create_edge_topic(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateEdgeTopicRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateEdgeTopicResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/danube.edge.EdgeReplicatorService/CreateEdgeTopic",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "danube.edge.EdgeReplicatorService",
                        "CreateEdgeTopic",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Replicate message batches from edge to cluster.
        ///
        /// * Bidirectional stream: edge sends batches, cluster acks offsets
        /// * Writes directly to WAL via Wal::append_batch() (no producer overhead)
        ///  Auth: requires Replicate permission on the topic's namespace.
        pub async fn replicate_data(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ReplicateBatch>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ReplicateAck>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/danube.edge.EdgeReplicatorService/ReplicateData",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("danube.edge.EdgeReplicatorService", "ReplicateData"),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod edge_replicator_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EdgeReplicatorServiceServer.
    #[async_trait]
    pub trait EdgeReplicatorService: std::marker::Send + std::marker::Sync + 'static {
        /// Create a topic on the cluster for edge replication.
        ///
        /// * Validates that the topic belongs to a namespace the caller has access to
        /// * Creates topic metadata (always Reliable dispatch strategy)
        /// * Creates WAL via StorageFactory
        ///  Auth: requires ManageTopic permission on the topic's namespace.
        async fn create_edge_topic(
            &self,
            request: tonic::Request<super::CreateEdgeTopicRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateEdgeTopicResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ReplicateData method.
        type ReplicateDataStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ReplicateAck, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Replicate message batches from edge to cluster.
        ///
        /// * Bidirectional stream: edge sends batches, cluster acks offsets
        /// * Writes directly to WAL via Wal::append_batch() (no producer overhead)
        ///  Auth: requires Replicate permission on the topic's namespace.
        async fn replicate_data(
            &self,
            request: tonic::Request<tonic::Streaming<super::ReplicateBatch>>,
        ) -> std::result::Result<
            tonic::Response<Self::ReplicateDataStream>,
            tonic::Status,
        >;
    }
    /// Edge → Cluster replication service.
    ///
    /// Hosted on the cluster broker's gRPC port, behind the standard auth interceptor.
    /// Edge brokers authenticate using the same mechanisms as any client:
    ///
    /// * JWT token (via `authorization` header) — scoped to the edge's namespace
    /// * mTLS + internal-broker header — for trusted infrastructure
    ///
    /// The admin pre-provisions: namespace, JWT token, RBAC binding with Replicate permission.
    #[derive(Debug)]
    pub struct EdgeReplicatorServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EdgeReplicatorServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for EdgeReplicatorServiceServer<T>
    where
        T: EdgeReplicatorService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/danube.edge.EdgeReplicatorService/CreateEdgeTopic" => {
                    #[allow(non_camel_case_types)]
                    struct CreateEdgeTopicSvc<T: EdgeReplicatorService>(pub Arc<T>);
                    impl<
                        T: EdgeReplicatorService,
                    > tonic::server::UnaryService<super::CreateEdgeTopicRequest>
                    for CreateEdgeTopicSvc<T> {
                        type Response = super::CreateEdgeTopicResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateEdgeTopicRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EdgeReplicatorService>::create_edge_topic(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateEdgeTopicSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/danube.edge.EdgeReplicatorService/ReplicateData" => {
                    #[allow(non_camel_case_types)]
                    struct ReplicateDataSvc<T: EdgeReplicatorService>(pub Arc<T>);
                    impl<
                        T: EdgeReplicatorService,
                    > tonic::server::StreamingService<super::ReplicateBatch>
                    for ReplicateDataSvc<T> {
                        type Response = super::ReplicateAck;
                        type ResponseStream = T::ReplicateDataStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::ReplicateBatch>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EdgeReplicatorService>::replicate_data(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReplicateDataSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EdgeReplicatorServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "danube.edge.EdgeReplicatorService";
    impl<T> tonic::server::NamedService for EdgeReplicatorServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
