// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterEdgeRequest {
    /// e.g. "edge1"
    #[prost(string, tag = "1")]
    pub edge_name: ::prost::alloc::string::String,
    /// Full list of topics from config
    #[prost(message, repeated, tag = "2")]
    pub topics: ::prost::alloc::vec::Vec<EdgeTopicDeclaration>,
}
/// A topic declared in the edge's config (edge.yaml).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EdgeTopicDeclaration {
    /// e.g. "/edge1/telemetry"
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    /// e.g. "telemetry-events" (absent = raw bytes)
    #[prost(string, optional, tag = "2")]
    pub schema_subject: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterEdgeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Initial config version from Raft
    #[prost(uint64, tag = "3")]
    pub config_version: u64,
    /// Per-topic resolution results
    #[prost(message, repeated, tag = "4")]
    pub topics: ::prost::alloc::vec::Vec<TopicRegistrationResult>,
}
/// Result of registering a single topic during RegisterEdge.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TopicRegistrationResult {
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    /// true if newly created on cluster
    #[prost(bool, tag = "2")]
    pub topic_created: bool,
    /// true if schema_subject found in registry
    #[prost(bool, tag = "3")]
    pub schema_resolved: bool,
    /// Full schema info (only if resolved)
    #[prost(message, optional, tag = "4")]
    pub schema: ::core::option::Option<ResolvedSchema>,
    /// Non-empty if topic/schema setup failed
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
}
/// Schema definition resolved by the cluster from its registry.
/// Sent to the edge so it can cache and validate MQTT payloads locally.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolvedSchema {
    #[prost(string, tag = "1")]
    pub subject: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub schema_id: u64,
    #[prost(uint32, tag = "3")]
    pub schema_version: u32,
    /// "json_schema", "avro", "protobuf", etc.
    #[prost(string, tag = "4")]
    pub schema_type: ::prost::alloc::string::String,
    /// Full definition for edge to cache
    #[prost(bytes = "vec", tag = "5")]
    pub schema_definition: ::prost::alloc::vec::Vec<u8>,
    /// SHA-256 for change detection
    #[prost(string, tag = "6")]
    pub fingerprint: ::prost::alloc::string::String,
    /// "none", "backward", "forward", "full"
    #[prost(string, tag = "7")]
    pub compatibility_mode: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EdgeHeartbeatRequest {
    #[prost(string, tag = "1")]
    pub edge_name: ::prost::alloc::string::String,
    /// Edge's current config version
    #[prost(uint64, tag = "2")]
    pub config_version: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EdgeHeartbeatResponse {
    /// false = fast path, nothing to do
    #[prost(bool, tag = "1")]
    pub changed: bool,
    /// Current version (same if changed=false)
    #[prost(uint64, tag = "2")]
    pub config_version: u64,
    /// Only populated if changed=true
    #[prost(message, repeated, tag = "3")]
    pub changes: ::prost::alloc::vec::Vec<EdgeChange>,
}
/// A single change detected during heartbeat.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EdgeChange {
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    #[prost(enumeration = "EdgeChangeType", tag = "2")]
    pub change_type: i32,
    /// Set for SCHEMA_UPDATED
    #[prost(message, optional, tag = "3")]
    pub schema: ::core::option::Option<ResolvedSchema>,
    /// Human-readable context
    #[prost(string, tag = "4")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicateBatch {
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    /// Full messages from edge WAL
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<super::StreamMessage>,
    /// Idempotency key (highest edge offset)
    #[prost(uint64, tag = "3")]
    pub batch_last_offset: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplicateAck {
    #[prost(string, tag = "1")]
    pub topic_name: ::prost::alloc::string::String,
    /// Echoes batch_last_offset on success
    #[prost(uint64, tag = "2")]
    pub acked_offset: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EdgeChangeType {
    /// Schema subject has a new version on the cluster
    SchemaUpdated = 0,
    /// Schema subject was deleted from cluster registry
    SchemaRemoved = 1,
    /// Topic was deleted from cluster (admin action)
    TopicRemoved = 2,
}
impl EdgeChangeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SchemaUpdated => "SCHEMA_UPDATED",
            Self::SchemaRemoved => "SCHEMA_REMOVED",
            Self::TopicRemoved => "TOPIC_REMOVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCHEMA_UPDATED" => Some(Self::SchemaUpdated),
            "SCHEMA_REMOVED" => Some(Self::SchemaRemoved),
            "TOPIC_REMOVED" => Some(Self::TopicRemoved),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod edge_replicator_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Edge ↔ Cluster coordination and replication service.
    /// Hosted on cluster brokers, behind the standard auth interceptor.
    ///
    /// The edge is a constrained gateway for MQTT ingestion into the cloud.
    /// Topics are defined by edge config (edge.yaml) and registered with the
    /// cluster at startup. The cluster maintains per-edge state in Raft.
    #[derive(Debug, Clone)]
    pub struct EdgeReplicatorServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EdgeReplicatorServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EdgeReplicatorServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EdgeReplicatorServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EdgeReplicatorServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Register (or re-register) an edge broker with the cluster.
        /// Called once at startup. Creates topics on the cluster, resolves schemas
        /// from the cluster registry, and stores per-edge state in Raft.
        /// Idempotent: re-registration diffs against previous state.
        pub async fn register_edge(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterEdgeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterEdgeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/danube.edge.EdgeReplicatorService/RegisterEdge",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("danube.edge.EdgeReplicatorService", "RegisterEdge"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Periodic heartbeat + change detection.
        /// Edge sends its config_version; cluster compares against Raft state.
        /// Fast path: versions match → no changes. Slow path: returns changelog.
        pub async fn edge_heartbeat(
            &mut self,
            request: impl tonic::IntoRequest<super::EdgeHeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EdgeHeartbeatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/danube.edge.EdgeReplicatorService/EdgeHeartbeat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("danube.edge.EdgeReplicatorService", "EdgeHeartbeat"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Bidirectional stream: edge sends message batches, cluster acks offsets.
        /// Uses batch_last_offset as idempotency key to prevent duplicate writes.
        pub async fn replicate_data(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ReplicateBatch>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ReplicateAck>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/danube.edge.EdgeReplicatorService/ReplicateData",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("danube.edge.EdgeReplicatorService", "ReplicateData"),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod edge_replicator_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EdgeReplicatorServiceServer.
    #[async_trait]
    pub trait EdgeReplicatorService: std::marker::Send + std::marker::Sync + 'static {
        /// Register (or re-register) an edge broker with the cluster.
        /// Called once at startup. Creates topics on the cluster, resolves schemas
        /// from the cluster registry, and stores per-edge state in Raft.
        /// Idempotent: re-registration diffs against previous state.
        async fn register_edge(
            &self,
            request: tonic::Request<super::RegisterEdgeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterEdgeResponse>,
            tonic::Status,
        >;
        /// Periodic heartbeat + change detection.
        /// Edge sends its config_version; cluster compares against Raft state.
        /// Fast path: versions match → no changes. Slow path: returns changelog.
        async fn edge_heartbeat(
            &self,
            request: tonic::Request<super::EdgeHeartbeatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EdgeHeartbeatResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ReplicateData method.
        type ReplicateDataStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ReplicateAck, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Bidirectional stream: edge sends message batches, cluster acks offsets.
        /// Uses batch_last_offset as idempotency key to prevent duplicate writes.
        async fn replicate_data(
            &self,
            request: tonic::Request<tonic::Streaming<super::ReplicateBatch>>,
        ) -> std::result::Result<
            tonic::Response<Self::ReplicateDataStream>,
            tonic::Status,
        >;
    }
    /// Edge ↔ Cluster coordination and replication service.
    /// Hosted on cluster brokers, behind the standard auth interceptor.
    ///
    /// The edge is a constrained gateway for MQTT ingestion into the cloud.
    /// Topics are defined by edge config (edge.yaml) and registered with the
    /// cluster at startup. The cluster maintains per-edge state in Raft.
    #[derive(Debug)]
    pub struct EdgeReplicatorServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EdgeReplicatorServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for EdgeReplicatorServiceServer<T>
    where
        T: EdgeReplicatorService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/danube.edge.EdgeReplicatorService/RegisterEdge" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterEdgeSvc<T: EdgeReplicatorService>(pub Arc<T>);
                    impl<
                        T: EdgeReplicatorService,
                    > tonic::server::UnaryService<super::RegisterEdgeRequest>
                    for RegisterEdgeSvc<T> {
                        type Response = super::RegisterEdgeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterEdgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EdgeReplicatorService>::register_edge(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterEdgeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/danube.edge.EdgeReplicatorService/EdgeHeartbeat" => {
                    #[allow(non_camel_case_types)]
                    struct EdgeHeartbeatSvc<T: EdgeReplicatorService>(pub Arc<T>);
                    impl<
                        T: EdgeReplicatorService,
                    > tonic::server::UnaryService<super::EdgeHeartbeatRequest>
                    for EdgeHeartbeatSvc<T> {
                        type Response = super::EdgeHeartbeatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EdgeHeartbeatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EdgeReplicatorService>::edge_heartbeat(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EdgeHeartbeatSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/danube.edge.EdgeReplicatorService/ReplicateData" => {
                    #[allow(non_camel_case_types)]
                    struct ReplicateDataSvc<T: EdgeReplicatorService>(pub Arc<T>);
                    impl<
                        T: EdgeReplicatorService,
                    > tonic::server::StreamingService<super::ReplicateBatch>
                    for ReplicateDataSvc<T> {
                        type Response = super::ReplicateAck;
                        type ResponseStream = T::ReplicateDataStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::ReplicateBatch>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EdgeReplicatorService>::replicate_data(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReplicateDataSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EdgeReplicatorServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "danube.edge.EdgeReplicatorService";
    impl<T> tonic::server::NamedService for EdgeReplicatorServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
