name: Admin CLI E2E

on:
  pull_request:
    paths:
      - 'danube-admin-cli/**'
      - 'danube-broker/**'
      - 'danube-core/proto/DanubeAdmin.proto'

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.9
        ports:
          - 2379:2379
        options: >-
          --health-cmd "ETCDCTL_API=3 etcdctl endpoint health --endpoints=http://localhost:2379 || exit 1" 
          --health-interval 5s --health-timeout 5s --health-retries 20
        env:
          ETCD_NAME: etcd-danube
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_DATA_DIR: /etcd-data

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build workspace (release)
        run: cargo build --workspace --release

      - name: Start broker (background)
        env:
          RUST_LOG: info
        run: |
          nohup ./target/release/danube-broker \
            --config-file ./config/danube_broker.yml \
            --broker-addr 0.0.0.0:6650 \
            --admin-addr 0.0.0.0:50051 \
            --prom-exporter 0.0.0.0:9040 \
            > broker.log 2>&1 &
          # Wait for admin and discovery ports to be ready
          for i in {1..60}; do \
            (echo > /dev/tcp/127.0.0.1/50051) >/dev/null 2>&1 && \
            (echo > /dev/tcp/127.0.0.1/6650) >/dev/null 2>&1 && break; \
            sleep 1; \
          done
          echo "Broker started" && tail -n +1 broker.log | sed -n '1,40p'

      - name: Run admin CLI E2E tests
        env:
          DANUBE_ADMIN_ENDPOINT: http://127.0.0.1:50051
          DANUBE_BROKER_ENDPOINT: http://127.0.0.1:6650
        run: cargo test -p danube-admin-cli --tests -- --nocapture

      - name: Upload broker logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: broker-logs
          path: broker.log
